name:                hipsql-test
version:             0.0.0.0
github:              "simspace/hipsql"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2021 SimSpace"

description:         Please see the README on GitHub at <https://github.com/simspace/hipsql#readme>

dependencies:
- base >= 4.7 && < 5
- hipsql-client
- hipsql-server
- async
- bytestring
- http-client
- postgresql-libpq
- warp

ghc-options:
- -Wall

tests:
  hipsql-test:
    main: Spec.hs
    source-dirs: test-suite
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - postgresql-simple
