name:                hipsql-server
version:             0.0.0.0
github:              "simspace/hipsql"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2021 SimSpace"

extra-source-files:
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/simspace/hipsql#readme>

dependencies:
- base >= 4.7 && < 5
- hipsql-api >= 0.0 && < 0.1
- hipsql-monad >= 0.0 && < 0.1
- async >= 2.2.2 && < 2.3
- bytestring >= 0.10.10.0 && < 0.11
- mtl >= 2.2.2 && < 2.3
- postgresql-libpq >= 0.9.4.2 && < 0.10
- servant-server >= 0.16 && < 0.17
- warp >= 3.3.13 && < 3.4

ghc-options:
- -Wall

library:
  source-dirs: library

executables:
  hipsql-demo-server:
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hipsql-server
