name:                hipsql-api
version:             0.0.0.0
github:              "simspace/hipsql"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2021 SimSpace"

extra-source-files:
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/simspace/hipsql#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.4.7.1 && < 1.5
- bytestring >= 0.10.10.0 && < 0.11
- servant >= 0.16 && < 0.17

ghc-options:
- -Wall

library:
  source-dirs: library
