name:                hipsql
version:             0.0.0.0
github:              "simspace/hipsql"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 SimSpace"

extra-source-files:
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/simspace/hipsql#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.10.0 && < 0.11
- exceptions >= 0.10.4 && < 0.11
- haskeline >= 0.7.5.0 && < 0.8
- mtl >= 2.2.2 && < 2.3
- postgresql-libpq >= 0.9.4.2 && < 0.10
- transformers >= 0.5.6.2 && < 0.6

ghc-options:
- -Wall

library:
  source-dirs: library

executables:
  hipsql:
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hipsql

tests:
  hipsql-test:
    main: Spec.hs
    source-dirs: test-suite
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hipsql
    - async
    - hspec
    - postgresql-simple
